zope.exceptions-4.6-py3.9-nspkg.pth,sha256=SWEVH-jEWsKYrL0qoC6GBJaStx_iKxGoAY9PQycFVC4,529
zope.exceptions-4.6.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
zope.exceptions-4.6.dist-info/LICENSE.txt,sha256=PmcdsR32h1FswdtbPWXkqjg-rKPCDOo_r1Og9zNdCjw,2070
zope.exceptions-4.6.dist-info/METADATA,sha256=64aVY5wWRYEnfe7Dkvsa87PPFa_D80RykB8VV7ZVsL0,8420
zope.exceptions-4.6.dist-info/RECORD,,
zope.exceptions-4.6.dist-info/WHEEL,sha256=z9j0xAa_JmUKMpmz72K0ZGALSM_n-wQVmGbleXx2VHg,110
zope.exceptions-4.6.dist-info/namespace_packages.txt,sha256=QpUHvpO4wIuZDeEgKY8qZCtD-tAukB0fn_f6utzlb98,5
zope.exceptions-4.6.dist-info/top_level.txt,sha256=QpUHvpO4wIuZDeEgKY8qZCtD-tAukB0fn_f6utzlb98,5
zope/exceptions/__init__.py,sha256=3R7Va_j98Pri4qPXjCKgw9m2fFk_YP4Z_F0biSPvRjQ,2122
zope/exceptions/__pycache__/__init__.cpython-310.pyc,,
zope/exceptions/__pycache__/exceptionformatter.cpython-310.pyc,,
zope/exceptions/__pycache__/interfaces.cpython-310.pyc,,
zope/exceptions/__pycache__/log.cpython-310.pyc,,
zope/exceptions/exceptionformatter.py,sha256=AgTro-iFt_cBaFJyeabINuarqxcN7FH-ZgyNKu93pZ0,11973
zope/exceptions/interfaces.py,sha256=oVdJiEhKQqop4ZhpWL2yZxkWPgClCAYEAWcZaYy3-RA,3439
zope/exceptions/log.py,sha256=v6CiZnAAlCcb0FM_wCE0WZ2xS3OnZUHrOfiWOWC404o,1303
zope/exceptions/tests/__init__.py,sha256=MsSFjiLMLJZ7QhUPpVBWKiyDnCzryquRyr329NoCACI,2
zope/exceptions/tests/__pycache__/__init__.cpython-310.pyc,,
zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-310.pyc,,
zope/exceptions/tests/__pycache__/test_log.cpython-310.pyc,,
zope/exceptions/tests/test_exceptionformatter.py,sha256=kIFbOH1CV5XDV9PzKOAyySW2kkhzGOf-i5AxsKNa72g,35803
zope/exceptions/tests/test_log.py,sha256=C3XggAr62myOSWhdJDZF1BT_IKRcFlSOrcx2IfHIErQ,3000
